/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BudgetCategory = { 'taxes' : null } |
  { 'entertainment' : null } |
  { 'food' : null } |
  { 'rent' : null } |
  { 'transport' : null } |
  { 'education' : null } |
  { 'others' : null } |
  { 'maintenance' : null } |
  { 'shopping' : null } |
  { 'electricityBill' : null } |
  { 'waterCharges' : null } |
  { 'medical' : null };
export interface BudgetLimit {
  'id' : bigint,
  'month' : string,
  'monthlyLimit' : number,
  'createdBy' : Principal,
  'category' : BudgetCategory,
}
export interface Expense {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'createdAt' : Time,
  'notes' : string,
  'category' : BudgetCategory,
  'amount' : number,
  'shareAmount' : [] | [number],
  'paidBy' : Principal,
}
export interface Income {
  'id' : bigint,
  'source' : string,
  'date' : string,
  'addedBy' : Principal,
  'amount' : number,
}
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'notificationType' : string,
  'createdAt' : string,
  'isRead' : boolean,
  'message' : string,
}
export interface SavingsGoal {
  'id' : bigint,
  'name' : string,
  'createdBy' : Principal,
  'deadline' : string,
  'targetAmount' : number,
  'currentAmount' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBudgetLimit' : ActorMethod<[BudgetCategory, number, string], bigint>,
  'createExpense' : ActorMethod<
    [string, number, BudgetCategory, string, string, [] | [number]],
    bigint
  >,
  'createIncome' : ActorMethod<[string, number, string], bigint>,
  'createNotification' : ActorMethod<
    [string, string, Principal, string],
    bigint
  >,
  'createSavingsGoal' : ActorMethod<[string, number, string], bigint>,
  'deleteBudgetLimit' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteIncome' : ActorMethod<[bigint], undefined>,
  'deleteNotification' : ActorMethod<[bigint], undefined>,
  'deleteSavingsGoal' : ActorMethod<[bigint], undefined>,
  'demoteAdminToMember' : ActorMethod<[Principal], undefined>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllIncome' : ActorMethod<[], Array<Income>>,
  'getAllSavingsGoals' : ActorMethod<[], Array<SavingsGoal>>,
  'getBudgetLimitsByMonth' : ActorMethod<[string], Array<BudgetLimit>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpensesByCategory' : ActorMethod<[BudgetCategory], Array<Expense>>,
  'getExpensesByCategoryForMonth' : ActorMethod<
    [BudgetCategory, string],
    Array<Expense>
  >,
  'getExpensesByMember' : ActorMethod<[Principal], Array<Expense>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getTotalExpensesForMonth' : ActorMethod<[string], number>,
  'getTotalIncomeForMonth' : ActorMethod<[string], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'promoteMemberToAdmin' : ActorMethod<[Principal], undefined>,
  'readBudgetLimit' : ActorMethod<[bigint], BudgetLimit>,
  'readExpense' : ActorMethod<[bigint], Expense>,
  'readIncome' : ActorMethod<[bigint], Income>,
  'readNotification' : ActorMethod<[bigint], Notification>,
  'readSavingsGoal' : ActorMethod<[bigint], SavingsGoal>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBudgetLimit' : ActorMethod<
    [bigint, BudgetCategory, number, string],
    undefined
  >,
  'updateExpense' : ActorMethod<
    [bigint, string, number, BudgetCategory, string, string, [] | [number]],
    undefined
  >,
  'updateIncome' : ActorMethod<[bigint, string, number, string], undefined>,
  'updateSavingsGoal' : ActorMethod<
    [bigint, string, number, number, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];