/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BudgetCategory = IDL.Variant({
  'taxes' : IDL.Null,
  'entertainment' : IDL.Null,
  'food' : IDL.Null,
  'rent' : IDL.Null,
  'transport' : IDL.Null,
  'education' : IDL.Null,
  'others' : IDL.Null,
  'maintenance' : IDL.Null,
  'shopping' : IDL.Null,
  'electricityBill' : IDL.Null,
  'waterCharges' : IDL.Null,
  'medical' : IDL.Null,
});
export const Time = IDL.Int;
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Time,
  'notes' : IDL.Text,
  'category' : BudgetCategory,
  'amount' : IDL.Float64,
  'shareAmount' : IDL.Opt(IDL.Float64),
  'paidBy' : IDL.Principal,
});
export const Income = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'date' : IDL.Text,
  'addedBy' : IDL.Principal,
  'amount' : IDL.Float64,
});
export const SavingsGoal = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'deadline' : IDL.Text,
  'targetAmount' : IDL.Float64,
  'currentAmount' : IDL.Float64,
});
export const BudgetLimit = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Text,
  'monthlyLimit' : IDL.Float64,
  'createdBy' : IDL.Principal,
  'category' : BudgetCategory,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'notificationType' : IDL.Text,
  'createdAt' : IDL.Text,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBudgetLimit' : IDL.Func(
      [BudgetCategory, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createExpense' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        BudgetCategory,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
      ],
      [IDL.Nat],
      [],
    ),
  'createIncome' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [IDL.Nat], []),
  'createNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Principal, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createSavingsGoal' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteBudgetLimit' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteIncome' : IDL.Func([IDL.Nat], [], []),
  'deleteNotification' : IDL.Func([IDL.Nat], [], []),
  'deleteSavingsGoal' : IDL.Func([IDL.Nat], [], []),
  'demoteAdminToMember' : IDL.Func([IDL.Principal], [], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllIncome' : IDL.Func([], [IDL.Vec(Income)], ['query']),
  'getAllSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
  'getBudgetLimitsByMonth' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BudgetLimit)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpensesByCategory' : IDL.Func(
      [BudgetCategory],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getExpensesByCategoryForMonth' : IDL.Func(
      [BudgetCategory, IDL.Text],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getExpensesByMember' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getTotalExpensesForMonth' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getTotalIncomeForMonth' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'promoteMemberToAdmin' : IDL.Func([IDL.Principal], [], []),
  'readBudgetLimit' : IDL.Func([IDL.Nat], [BudgetLimit], ['query']),
  'readExpense' : IDL.Func([IDL.Nat], [Expense], ['query']),
  'readIncome' : IDL.Func([IDL.Nat], [Income], ['query']),
  'readNotification' : IDL.Func([IDL.Nat], [Notification], ['query']),
  'readSavingsGoal' : IDL.Func([IDL.Nat], [SavingsGoal], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBudgetLimit' : IDL.Func(
      [IDL.Nat, BudgetCategory, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateExpense' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        BudgetCategory,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
      ],
      [],
      [],
    ),
  'updateIncome' : IDL.Func([IDL.Nat, IDL.Text, IDL.Float64, IDL.Text], [], []),
  'updateSavingsGoal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BudgetCategory = IDL.Variant({
    'taxes' : IDL.Null,
    'entertainment' : IDL.Null,
    'food' : IDL.Null,
    'rent' : IDL.Null,
    'transport' : IDL.Null,
    'education' : IDL.Null,
    'others' : IDL.Null,
    'maintenance' : IDL.Null,
    'shopping' : IDL.Null,
    'electricityBill' : IDL.Null,
    'waterCharges' : IDL.Null,
    'medical' : IDL.Null,
  });
  const Time = IDL.Int;
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Time,
    'notes' : IDL.Text,
    'category' : BudgetCategory,
    'amount' : IDL.Float64,
    'shareAmount' : IDL.Opt(IDL.Float64),
    'paidBy' : IDL.Principal,
  });
  const Income = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'date' : IDL.Text,
    'addedBy' : IDL.Principal,
    'amount' : IDL.Float64,
  });
  const SavingsGoal = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'deadline' : IDL.Text,
    'targetAmount' : IDL.Float64,
    'currentAmount' : IDL.Float64,
  });
  const BudgetLimit = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Text,
    'monthlyLimit' : IDL.Float64,
    'createdBy' : IDL.Principal,
    'category' : BudgetCategory,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'notificationType' : IDL.Text,
    'createdAt' : IDL.Text,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBudgetLimit' : IDL.Func(
        [BudgetCategory, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createExpense' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          BudgetCategory,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
        ],
        [IDL.Nat],
        [],
      ),
    'createIncome' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text], [IDL.Nat], []),
    'createNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Principal, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createSavingsGoal' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteBudgetLimit' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteIncome' : IDL.Func([IDL.Nat], [], []),
    'deleteNotification' : IDL.Func([IDL.Nat], [], []),
    'deleteSavingsGoal' : IDL.Func([IDL.Nat], [], []),
    'demoteAdminToMember' : IDL.Func([IDL.Principal], [], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllIncome' : IDL.Func([], [IDL.Vec(Income)], ['query']),
    'getAllSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
    'getBudgetLimitsByMonth' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BudgetLimit)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpensesByCategory' : IDL.Func(
        [BudgetCategory],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByCategoryForMonth' : IDL.Func(
        [BudgetCategory, IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByMember' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getTotalExpensesForMonth' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getTotalIncomeForMonth' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'promoteMemberToAdmin' : IDL.Func([IDL.Principal], [], []),
    'readBudgetLimit' : IDL.Func([IDL.Nat], [BudgetLimit], ['query']),
    'readExpense' : IDL.Func([IDL.Nat], [Expense], ['query']),
    'readIncome' : IDL.Func([IDL.Nat], [Income], ['query']),
    'readNotification' : IDL.Func([IDL.Nat], [Notification], ['query']),
    'readSavingsGoal' : IDL.Func([IDL.Nat], [SavingsGoal], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBudgetLimit' : IDL.Func(
        [IDL.Nat, BudgetCategory, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateExpense' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          BudgetCategory,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
        ],
        [],
        [],
      ),
    'updateIncome' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateSavingsGoal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };