/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Notification {
    id: bigint;
    userId: Principal;
    notificationType: string;
    createdAt: string;
    isRead: boolean;
    message: string;
}
export interface Income {
    id: bigint;
    source: string;
    date: string;
    addedBy: Principal;
    amount: number;
}
export interface BudgetLimit {
    id: bigint;
    month: string;
    monthlyLimit: number;
    createdBy: Principal;
    category: BudgetCategory;
}
export interface Expense {
    id: bigint;
    title: string;
    date: string;
    createdAt: Time;
    notes: string;
    category: BudgetCategory;
    amount: number;
    shareAmount?: number;
    paidBy: Principal;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface SavingsGoal {
    id: bigint;
    name: string;
    createdBy: Principal;
    deadline: string;
    targetAmount: number;
    currentAmount: number;
}
export enum BudgetCategory {
    taxes = "taxes",
    entertainment = "entertainment",
    food = "food",
    rent = "rent",
    transport = "transport",
    education = "education",
    others = "others",
    maintenance = "maintenance",
    shopping = "shopping",
    electricityBill = "electricityBill",
    waterCharges = "waterCharges",
    medical = "medical"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBudgetLimit(category: BudgetCategory, monthlyLimit: number, month: string): Promise<bigint>;
    createExpense(title: string, amount: number, category: BudgetCategory, date: string, notes: string, shareAmount: number | null): Promise<bigint>;
    createIncome(source: string, amount: number, date: string): Promise<bigint>;
    createNotification(message: string, notificationType: string, userId: Principal, createdAt: string): Promise<bigint>;
    createSavingsGoal(name: string, targetAmount: number, deadline: string): Promise<bigint>;
    deleteBudgetLimit(id: bigint): Promise<void>;
    deleteExpense(id: bigint): Promise<void>;
    deleteIncome(id: bigint): Promise<void>;
    deleteNotification(id: bigint): Promise<void>;
    deleteSavingsGoal(id: bigint): Promise<void>;
    demoteAdminToMember(user: Principal): Promise<void>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllIncome(): Promise<Array<Income>>;
    getAllSavingsGoals(): Promise<Array<SavingsGoal>>;
    getBudgetLimitsByMonth(month: string): Promise<Array<BudgetLimit>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExpensesByCategory(category: BudgetCategory): Promise<Array<Expense>>;
    getExpensesByCategoryForMonth(category: BudgetCategory, month: string): Promise<Array<Expense>>;
    getExpensesByMember(member: Principal): Promise<Array<Expense>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getTotalExpensesForMonth(month: string): Promise<number>;
    getTotalIncomeForMonth(month: string): Promise<number>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(id: bigint): Promise<void>;
    promoteMemberToAdmin(user: Principal): Promise<void>;
    readBudgetLimit(id: bigint): Promise<BudgetLimit>;
    readExpense(id: bigint): Promise<Expense>;
    readIncome(id: bigint): Promise<Income>;
    readNotification(id: bigint): Promise<Notification>;
    readSavingsGoal(id: bigint): Promise<SavingsGoal>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBudgetLimit(id: bigint, category: BudgetCategory, monthlyLimit: number, month: string): Promise<void>;
    updateExpense(id: bigint, title: string, amount: number, category: BudgetCategory, date: string, notes: string, shareAmount: number | null): Promise<void>;
    updateIncome(id: bigint, source: string, amount: number, date: string): Promise<void>;
    updateSavingsGoal(id: bigint, name: string, targetAmount: number, currentAmount: number, deadline: string): Promise<void>;
}
import type { BudgetCategory as _BudgetCategory, BudgetLimit as _BudgetLimit, Expense as _Expense, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBudgetLimit(arg0: BudgetCategory, arg1: number, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBudgetLimit(to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBudgetLimit(to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async createExpense(arg0: string, arg1: number, arg2: BudgetCategory, arg3: string, arg4: string, arg5: number | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(arg0, arg1, to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(arg0, arg1, to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createIncome(arg0: string, arg1: number, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createIncome(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIncome(arg0, arg1, arg2);
            return result;
        }
    }
    async createNotification(arg0: string, arg1: string, arg2: Principal, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createSavingsGoal(arg0: string, arg1: number, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSavingsGoal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSavingsGoal(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteBudgetLimit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudgetLimit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudgetLimit(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteIncome(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncome(arg0);
            return result;
        }
    }
    async deleteNotification(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotification(arg0);
            return result;
        }
    }
    async deleteSavingsGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSavingsGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSavingsGoal(arg0);
            return result;
        }
    }
    async demoteAdminToMember(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.demoteAdminToMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.demoteAdminToMember(arg0);
            return result;
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIncome(): Promise<Array<Income>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncome();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncome();
            return result;
        }
    }
    async getAllSavingsGoals(): Promise<Array<SavingsGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSavingsGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSavingsGoals();
            return result;
        }
    }
    async getBudgetLimitsByMonth(arg0: string): Promise<Array<BudgetLimit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetLimitsByMonth(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetLimitsByMonth(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesByCategory(arg0: BudgetCategory): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByCategory(to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByCategory(to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesByCategoryForMonth(arg0: BudgetCategory, arg1: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByCategoryForMonth(to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByCategoryForMonth(to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesByMember(arg0: Principal): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByMember(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByMember(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return result;
        }
    }
    async getTotalExpensesForMonth(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalExpensesForMonth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalExpensesForMonth(arg0);
            return result;
        }
    }
    async getTotalIncomeForMonth(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalIncomeForMonth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalIncomeForMonth(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async promoteMemberToAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.promoteMemberToAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.promoteMemberToAdmin(arg0);
            return result;
        }
    }
    async readBudgetLimit(arg0: bigint): Promise<BudgetLimit> {
        if (this.processError) {
            try {
                const result = await this.actor.readBudgetLimit(arg0);
                return from_candid_BudgetLimit_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readBudgetLimit(arg0);
            return from_candid_BudgetLimit_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async readExpense(arg0: bigint): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.readExpense(arg0);
                return from_candid_Expense_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readExpense(arg0);
            return from_candid_Expense_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async readIncome(arg0: bigint): Promise<Income> {
        if (this.processError) {
            try {
                const result = await this.actor.readIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readIncome(arg0);
            return result;
        }
    }
    async readNotification(arg0: bigint): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.readNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readNotification(arg0);
            return result;
        }
    }
    async readSavingsGoal(arg0: bigint): Promise<SavingsGoal> {
        if (this.processError) {
            try {
                const result = await this.actor.readSavingsGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.readSavingsGoal(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBudgetLimit(arg0: bigint, arg1: BudgetCategory, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudgetLimit(arg0, to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudgetLimit(arg0, to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: string, arg2: number, arg3: BudgetCategory, arg4: string, arg5: string, arg6: number | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1, arg2, to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1, arg2, to_candid_BudgetCategory_n3(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateIncome(arg0: bigint, arg1: string, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncome(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncome(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateSavingsGoal(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSavingsGoal(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSavingsGoal(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_BudgetCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetCategory): BudgetCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_BudgetLimit_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetLimit): BudgetLimit {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    month: string;
    monthlyLimit: number;
    createdBy: Principal;
    category: _BudgetCategory;
}): {
    id: bigint;
    month: string;
    monthlyLimit: number;
    createdBy: Principal;
    category: BudgetCategory;
} {
    return {
        id: value.id,
        month: value.month,
        monthlyLimit: value.monthlyLimit,
        createdBy: value.createdBy,
        category: from_candid_BudgetCategory_n9(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: string;
    createdAt: _Time;
    notes: string;
    category: _BudgetCategory;
    amount: number;
    shareAmount: [] | [number];
    paidBy: Principal;
}): {
    id: bigint;
    title: string;
    date: string;
    createdAt: Time;
    notes: string;
    category: BudgetCategory;
    amount: number;
    shareAmount?: number;
    paidBy: Principal;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        createdAt: value.createdAt,
        notes: value.notes,
        category: from_candid_BudgetCategory_n9(_uploadFile, _downloadFile, value.category),
        amount: value.amount,
        shareAmount: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.shareAmount)),
        paidBy: value.paidBy
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxes: null;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    rent: null;
} | {
    transport: null;
} | {
    education: null;
} | {
    others: null;
} | {
    maintenance: null;
} | {
    shopping: null;
} | {
    electricityBill: null;
} | {
    waterCharges: null;
} | {
    medical: null;
}): BudgetCategory {
    return "taxes" in value ? BudgetCategory.taxes : "entertainment" in value ? BudgetCategory.entertainment : "food" in value ? BudgetCategory.food : "rent" in value ? BudgetCategory.rent : "transport" in value ? BudgetCategory.transport : "education" in value ? BudgetCategory.education : "others" in value ? BudgetCategory.others : "maintenance" in value ? BudgetCategory.maintenance : "shopping" in value ? BudgetCategory.shopping : "electricityBill" in value ? BudgetCategory.electricityBill : "waterCharges" in value ? BudgetCategory.waterCharges : "medical" in value ? BudgetCategory.medical : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BudgetLimit>): Array<BudgetLimit> {
    return value.map((x)=>from_candid_BudgetLimit_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n7(_uploadFile, _downloadFile, x));
}
function to_candid_BudgetCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetCategory): _BudgetCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetCategory): {
    taxes: null;
} | {
    entertainment: null;
} | {
    food: null;
} | {
    rent: null;
} | {
    transport: null;
} | {
    education: null;
} | {
    others: null;
} | {
    maintenance: null;
} | {
    shopping: null;
} | {
    electricityBill: null;
} | {
    waterCharges: null;
} | {
    medical: null;
} {
    return value == BudgetCategory.taxes ? {
        taxes: null
    } : value == BudgetCategory.entertainment ? {
        entertainment: null
    } : value == BudgetCategory.food ? {
        food: null
    } : value == BudgetCategory.rent ? {
        rent: null
    } : value == BudgetCategory.transport ? {
        transport: null
    } : value == BudgetCategory.education ? {
        education: null
    } : value == BudgetCategory.others ? {
        others: null
    } : value == BudgetCategory.maintenance ? {
        maintenance: null
    } : value == BudgetCategory.shopping ? {
        shopping: null
    } : value == BudgetCategory.electricityBill ? {
        electricityBill: null
    } : value == BudgetCategory.waterCharges ? {
        waterCharges: null
    } : value == BudgetCategory.medical ? {
        medical: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
